name: EukMS
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.6.9
  - augustus=3.3.3
  - gffread=0.12.1
  - gffcompare=0.11.2
  - mmseqs2=12.113e3
  - repeatmodeler=2.0.1
  - repeatmasker=4.0.9_p2
  - sqlite=3.33
  - sambamba=0.7.1
  - bedtools=2.29.2
  - hisat2=2.2.1
  - gmap=2020.06.30
  - braker2=2.1.2
  - bcbio-gff=0.6.6
  - biopython=1.76
  - plumbum=1.6.6
  - dask[distributed]=2.10.1
  - perl-mce=1.837
  - perl-math-utils=1.13
  - perl-yaml=1.28
  - perl-hash-merge=0.300
  - perl-logger-simple=2.0
  - perl-parallel-forkmanager=2.02
  - perl-threaded=5.26.0