name: EukMS
channels:
  - bioconda
  - conda-forge
  - anaconda
dependencies:
  - python=3.6
  - augustus
  - gffread
  - gffcompare
  - mmseqs2
  - pip
  - repeatmodeler
  - repeatmasker
  - sqlite=3.33
  - sambamba
  - bedtools
  - hisat2
  - braker2
  - maker