---  # document start

###########################################
## Pipeline input section
INPUT:
  run: all

## Global settings
GLOBAL:
  # Maximum threads/cpus to use in analysis
  MaxThreads: 24
  # Maximum memory to use (in GB)
  MaxMemory: 100

###########################################

SLURM:
  ## Set to True if using SLURM
  USE_CLUSTER: false
  ## Pass any flags you wish below
  ## DO NOT PASS the following:
  ## --nodes, --ntasks, --mem, --cpus-per-task
  --qos: unlim
  --job-name: EukMS
  user-id: uid

CollectInput:
  # Number of threads task will use
  threads: 1
  # Amount of memory task will use (in GB)
  memory: 8
  time: "4:00:00"
  # Should be in format (excluding spaces around tab):
  # file-basename \t /path/to/tr1.fna[,/path/to/tr2.fna]
  transcriptomes: /path/to/transcriptome-mapping-file
  # Should be in format (excluding spaces around tab):
  # file-basename \t /path/to/r1.fq[,/path/to/r2.fq][;/path/to/r3.fq[,/path/to/r4.fq]]
  rnaseq: /home/user/BioProjects/YAPIM/tests/eukmetasanity/refine/rnaseq-mapping.list

GatherProteins:
  # Number of threads task will use
  threads: 8
  # Amount of memory task will use (in GB)
  memory: 8
  time: "4:00:00"
  dependencies:
    MMSeqsFilterTaxSeqDB:
      program: mmseqs
      level: order
      data:
        /media/user/2TB/Data/EukMetaSanity/data/odb-mmetsp_db

Transcriptomes:
  # Number of threads task will use
  threads: 8
  # Amount of memory task will use (in GB)
  memory: 8
  time: "4:00:00"
  dependencies:
    GMAPBuild:
      threads: 1
      program: gmapindex

    GMAP:
      program: gmap
      FLAGS:
        -B 5
        --input-buffer-size 1000000
        --output-buffer-size 1000000
        -f samse

RNASeq:
  # Number of threads task will use
  threads: 8
  # Amount of memory task will use (in GB)
  memory: 8
  time: "4:00:00"
  dependencies:
    Hisat2Build:
      threads: 1
      program: hisat2-build

    Hisat2:
      program: hisat2
      FLAGS:
        ""

MergeSams:
  # Number of threads task will use
  threads: 1
  # Amount of memory task will use (in GB)
  memory: 8
  time: "4:00:00"

ProcessMapping:
  # Number of threads task will use
  threads: 8
  # Amount of memory task will use (in GB)
  memory: 60
  time: "4:00:00"
  dependencies:
    SambambaView:
      program: sambamba

    SambambaSort:
      program: sambamba

RunBraker:
  # Number of threads task will use
  threads: 4
  # Amount of memory task will use (in GB)
  memory: 100
  time: "4:00:00"
  dependencies:
    Braker:
      program: braker.pl
      FLAGS:
      # Provide flags as desired

...  # document end