---  # document start

###########################################
## Pipeline input section
INPUT:
  root: all
  run:
    prot: genemark-prot

## Global settings
GLOBAL:
  # Maximum threads/cpus to use in analysis
  MaxThreads: 20
  # Maximum memory to use (in GB)
  MaxMemory: 100

###########################################

SLURM:
  ## Set to True if using SLURM
  USE_CLUSTER: false
  ## Pass any flags you wish below
  ## DO NOT PASS the following:
  ## --nodes, --ntasks, --mem, --cpus-per-task
  --qos: unlim
  --job-name: EukMS
  user-id: uid

Quality:
  # Number of threads task will use
  threads: 16
  # Amount of memory task will use (in GB)
  memory: 8
  time: "4:00:00"
  skip: false
  dependencies:
    Busco:
      program: busco
      mode: prot
      lineage: eukaryota
      FLAGS:
        -f

MMSeqs:
  # Number of threads task will use
  threads: 16
  # Amount of memory task will use (in GB)
  memory: 90
  time: "4:00:00"
  skip: false
  dependencies:
    MMSeqsCreateDB:
      program: mmseqs

    MMSeqsSearch:
      data:
        /media/user/2TB/Data/EukMetaSanity/data/odb-mmetsp_db
      program: mmseqs
      subname: linsearch
      FLAGS:
        --split-memory-limit 75G
        -c 0.3
        --cov-mode 1
        --remove-tmp-files

    MMSeqsConvertAlis:
      data:
        /media/user/2TB/Data/EukMetaSanity/data/odb-mmetsp_db
      program: mmseqs

KOFamScan:
  # Number of threads task will use
  threads: 1
  # Amount of memory task will use (in GB)
  memory: 8
  time: "4:00:00"
  skip: true
  dependencies:
    KofamscanExecAnnotation:
      program: /path/to/kofamscan/exec_annotation
      kolist: /path/to/kofam/ko_list
      profiles: /path/to/profiles/eukaryote.hal

EggNog:
  # Number of threads task will use
  threads: 1
  # Amount of memory task will use (in GB)
  memory: 8
  time: "4:00:00"
  skip: true
  dependencies:
    EMapper:
      program: /path/to/emapper.py
      python: /path/to/python2.7
      FLAGS:
        # Provide flags as needed
        -m diamond

...  # document end