name: EukMS_run
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8.6
  - augustus=3.4.0
  - gffread=0.12.1
  - mmseqs2=12.113e3
  - repeatmodeler=2.0.1
  - repeatmasker=4.0.9_p2
  - perl-mce=1.837
  - perl-yaml=1.28
  - perl-hash-merge=0.300
  - perl-logger-simple=2.0
  - perl-parallel-forkmanager=2.02
  - perl-threaded=5.26.0
  - perl-math-utils=1.13
  - pip
  - pip:
    - bcbio-gff==0.6.6
    - biopython==1.76
    - plumbum==1.6.6
    - networkx==2.2
    - pyyaml==5.3.1
    - art==5.1
    - pylint==2.6.0
    - pytest==6.2.1
    - pytest-cov==2.10.1
    - git+https://github.com/cjneely10/LocusSolver.git
    - git+https://github.com/cjneely10/YAPIM.git