[package]
name = "merge-annotations"
version = "0.1.0"
authors = ["Christopher Neely <christopher.neely1200@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "*"
argparse = "0.2.2"