name: EukMS_refine
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8.6
  - gffread=0.12.1
  - mmseqs2=12.113e3
  - sqlite=3.33
  - sambamba=0.7.1
  - bedtools=2.29.2
  - hisat2=2.2.1
  - gmap=2020.06.30
  - braker2=2.1.2
  - perl-mce=1.837
  - perl-math-utils=1.13
  - perl-yaml=1.28
  - perl-hash-merge=0.300
  - perl-logger-simple=2.0
  - perl-parallel-forkmanager=2.02
  - perl-threaded=5.26.0
  - pip
  - pip:
    - bcbio-gff==0.6.6
    - biopython==1.76
    - plumbum==1.6.6
    - networkx==2.2
    - pyyaml==5.3.1
    - art==5.1
    - pylint==2.6.0
    - pytest==6.2.1
    - pytest-cov==2.10.1
    - git+https://github.com/cjneely10/YAPIM.git
