---  # document start

###########################################
## Pipeline input section
INPUT:
  root: all

## Global settings
GLOBAL:
  # Maximum threads/cpus to use in analysis
  MaxThreads: 20
  # Maximum memory to use (in GB)
  MaxMemory: 120

###########################################

SLURM:
  ## Set to True if using SLURM
  USE_CLUSTER: false
  ## Pass any flags you wish below
  ## DO NOT PASS the following:
  ## --nodes, --ntasks, --mem, --cpus-per-task
  --qos: unlim
  --job-name: EukMS
  user-id: uid

MetaEukEV:
  # Number of threads task will use
  threads: 16
  # Amount of memory task will use (in GB)
  memory: 100
  time: "12:00:00"
  dependencies:
    MetaEuk:
      program: metaeuk
      data:
        /media/user/2TB/Data/EukMetaSanity/data/odb-mmetsp_db
      # Pass any flags to metaeuk required
      FLAGS:
        --min-length 30
        --metaeuk-eval 0.0001
        -s 5
        --cov-mode 0
        -c 0.3
        -e 100
        --max-overlap 0

Taxonomy:
  # Number of threads task will use
  threads: 16
  # Amount of memory task will use (in GB)
  memory: 100
  time: "8:00:00"
  dependencies:
    MMSeqsCreateDB:
      program: mmseqs
      threads: 1

    MMSeqsTaxonomy:
      program: mmseqs
      cutoff: 8.0  # Minimum % of mapped reads to tax level
      data:
        /media/user/2TB/Data/EukMetaSanity/data/odb-mmetsp_db
      # Pass any flags to mmseqs required
      FLAGS:
        --remove-tmp-files
        -s 6.5
        --min-seq-id 0.40
        -c 0.3
        --cov-mode 0

Repeats:
  # Number of threads task will use
  threads: 16
  # Amount of memory task will use (in GB)
  memory: 16
  time: "24:00:00"
  dependencies:
    RModBuildDatabase:
      time: "10:00"
      threads: 1
      program: BuildDatabase

    RModRepeatModeler:
      program: RepeatModeler
      skip: false

    RMaskRepeatMasker:
      program: RepeatMasker
      level: family
      data:
        "" # Comma-separated list of repeat models to incorporate
      FLAGS:
        -nolow

    RMaskProcessRepeats:
      time: "30:00"
      threads: 1
      program: ProcessRepeats
      FLAGS:
        -nolow

    RMaskRMOut:
      time: "10:00"
      threads: 1
      program: rmOutToGFF3.pl

AbinitioGeneMark:
  # Number of threads task will use
  threads: 16
  # Amount of memory task will use (in GB)
  memory: 16
  time: "16:00:00"
  skip: false
  dependencies:
    MMSeqsFilterTaxSeqDB:
      threads: 1
      time: "10:00"
      program: mmseqs
      level: order
      data:
        /media/user/2TB/Data/EukMetaSanity/data/odb-mmetsp_db

    GeneMarkProtHint:
      program: prothint.py

    GeneMarkPETAP:
      program: gmes_petap.pl
      FLAGS:
        --min_contig 100
        --max_contig 1000000000
        --max_gap 5000
        --max_mask 5000
        --min_contig_in_predict 100
        --min_gene_in_predict 10
        --gc_donor 0.001
        --max_intron 10000
        --max_intergenic 50000
        --soft_mask auto

AbinitioAugustus:
  # Number of threads task will use
  threads: 1
  # Amount of memory task will use (in GB)
  memory: 8
  time: "24:00:00"
  dependencies:
    MMSeqsCreateDB:
      time: "10:00"
      program: mmseqs
      threads: 1

    MMSeqsSearch:
      memory: 20
      threads: 10
      data:
        /media/user/2TB/Data/EukMetaSanity/data/odb-mmetsp_db
      program: mmseqs
      subname: linsearch  # Can use `search` if linear index is not present for database
      FLAGS:
        --split-memory-limit 16G
        --cov-mode 0
        -c 0.6
        -e 0.01
        --remove-tmp-files

    MMSeqsConvertAlis:
      time: "2:00:00"
      data:
        /media/user/2TB/Data/EukMetaSanity/data/odb-mmetsp_db
      program: mmseqs
      FLAGS:
        --format-output query,target,pident,taxid,taxname,taxlineage

    Augustus:
      threads: 1
      program: augustus
      cutoff: 25.0
      rounds: 1
      run_mode: genome  # Set to either genome or MAG

Tier:
  # Number of threads task will use
  threads: 1
  # Amount of memory task will use (in GB)
  memory: 8
  time: "10:00"
  program: locus_solver
  tier: 1  # or 2 or 3

...  # document end