name: EukMS_report
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8.6
  - mmseqs2=12.113e3
  - sqlite=3.33
  - busco=4.1.2
  - pip
  - pip:
    - bcbio-gff==0.6.6
    - biopython==1.76
    - plumbum==1.6.6
    - pyyaml==5.3.1
    - networkx==2.2
    - art==5.1
    - pylint==2.6.0
    - pytest==6.2.1
    - pytest-cov==2.10.1
    - git+https://github.com/cjneely10/YAPIM.git
